accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('login/', views.LoginView.as_view(), name='login'),
    # path('logout/', views.LogOutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogOutView.as_view(), name='logout'),
    ]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

birds_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from birds_app.views import MainPage, AddBird, BirdList, BirdDetails, AddCommentsView, AddBirdToWishlist, \
    EditBirdDetails, QuizView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', MainPage.as_view(), name='main'),
    path('add-bird/', AddBird.as_view(), name='add-bird'),
    path('bird-list/', BirdList.as_view(), name='bird-list'),
    path('bird/<int:id>/', BirdDetails.as_view(), name='bird-details'),
    path('bird/<int:id>/comment/', AddCommentsView.as_view(), name='add-comment'),
    path('wishlist/', AddBirdToWishlist.as_view(), name='wish-list'),
    path('bird/<int:id>/edit/', EditBirdDetails.as_view(), name='edit-bird'),
    path('quiz/', QuizView.as_view(), name='quiz'),
    path('quiz-results/', QuizView.as_view(), name='quiz-results'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from birds_app.views import MainPage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', MainPage.as_view(), name='main'),
    path('birds_app/', include('birds_app.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

birds_app/models.py
from django.conf.global_settings import AUTH_USER_MODEL
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Family(models.Model):
    name = models.CharField(max_length=24)

    def __str__(self):
        return self.name

class Region(models.Model):
    region = models.CharField(max_length=24)

    def __str__(self):
        return self.region

class Birds(models.Model):
    name = models.CharField(max_length=24)
    description = models.TextField(default="")
    population = models.IntegerField(null=True)
    region = models.ManyToManyField(Region)
    family = models.ForeignKey(Family, on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    approve = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_main_image_url(self):
        image = self.images_set.get(main=True)
        if image.image is None:
            return ""
        return image.image.url


class Images(models.Model):
    bird = models.ForeignKey(Birds, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to='images/', null=True, blank=True) # null = baza danych / blank = formularz
    description = models.TextField(default="")
    main = models.BooleanField(default=False)

    def __str__(self):
        return str(self.bird)

class Comments(models.Model):
    birds = models.ForeignKey(Birds, on_delete=models.CASCADE)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    approve = models.BooleanField(default=False)

    def __str__(self):
        return f'Comment on {self.birds} by {self.author}'

class Wishlist(models.Model):
    birds = models.ForeignKey(Birds, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.birds} by {self.user}'

class Quiz(models.Model):
    name = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True)

    def __str__(self):
        return self.name or ''

class Question(models.Model):
    question = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    def __str__(self):
        return self.question

class Answer(models.Model):
    answer = models.CharField(max_length=100)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return self.answer

class Carousel(models.Model):
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    title = models.CharField(max_length=150)
    action_name = models.CharField(max_length=50)

    def __str__(self):
        return self.title

birds_app/forms.py
from django import forms

from birds_app.models import Birds, Family, Comments, Wishlist, Quiz


class AddBirdForm(forms.ModelForm):
    family = forms.CharField()
    class Meta:
        model = Birds
        exclude = ['family', 'approve', 'author']

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['text']

class WishListForm(forms.ModelForm):

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        birds = Wishlist.objects.filter(user=user).values_list('birds', flat=True)
        birds = Birds.objects.exclude(id__in=birds)
        self.fields['birds'].queryset = birds
    class Meta:
        model = Wishlist
        fields = ['birds']

birds_app/views.py
import random
import datetime
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from accounts.forms import LoginFormView, RegisterFormView
from birds_app.forms import AddBirdForm, AddCommentForm, WishListForm
from birds_app.models import Birds, Family, Images, Comments, Region, Wishlist, Quiz, Question, Answer, Carousel


class MainPage(View):
    def get(self, request):
        # Random Bird of a day
        seed = f'{settings.SECRET_KEY}{datetime.date.today()}'
        random_bird = random.Random(seed).choice(Birds.objects.all())
        # Search engine
        name = request.GET.get('search', '')
        birds = Birds.objects.filter(name__icontains=name)
        # statistics
        birds_number = len(Birds.objects.all())
        users_number = len(User.objects.all())
        image_number = len(Images.objects.all())
        # carousel
        carousel = Carousel.objects.all()
        return render(request, 'main.html', {'birds': birds, 'random_bird': random_bird, 'birds_number': birds_number, 'users_number': users_number, 'image_number': image_number, 'carousel': carousel})

class AddBird(LoginRequiredMixin, View):
    def get(self, request):
        form = AddBirdForm()
        return render(request, 'add_bird.html', {'form': form})
    def post(self, request):
        form = AddBirdForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            population = form.cleaned_data['population']
            family, created = Family.objects.get_or_create(name=form.cleaned_data['family'])
            region = form.cleaned_data['region']
            bird = Birds.objects.create(name=name, description=description, population=population, family=family)
            bird.region.set(region)
            return redirect('main')
        return render(request, 'add_bird.html', {'form': form})

class BirdList(View):
    def get(self, request):
        birds = Birds.objects.all().order_by('name')
        return render(request, 'bird_list.html', {'birds': birds})

class BirdDetails(View):
    def get(self, request, id):
        bird = Birds.objects.get(pk=id)
        comments = bird.comments_set.filter(approve=True)
        return render(request, 'bird-details.html', {'bird': bird, 'comments': comments})

class EditBirdDetails(LoginRequiredMixin, View):
    def get(self, request, id):
        bird = Birds.objects.get(pk=id)
        comments = bird.comments_set.all()
        form = AddBirdForm(instance=bird)
        return render(request, 'bird-details.html', {'bird': bird, 'comments': comments, 'form': form})
    def post(self, request, id):
        bird = Birds.objects.get(pk=id)
        comments = bird.comments_set.all()
        form = AddBirdForm(request.POST, instance=bird)
        if form.is_valid():
            family, created = Family.objects.get_or_create(name=form.cleaned_data['family'])
            bird = form.save(commit=False)
            bird.family = family
            bird.save()
            return redirect(f'/birds_app/bird/{bird.id}/')
        return render(request, 'bird-details.html', {'bird': bird, 'comments': comments})


class AddCommentsView(LoginRequiredMixin, View):
    def get(self, request, id):
        bird = Birds.objects.get(pk=id)
        form = AddCommentForm()
        return render(request, 'bird-details.html', {'form': form, 'bird': bird})
    def post(self, request, id):
        bird = Birds.objects.get(pk=id)
        form = AddCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.birds = bird
            comment.save()
            return redirect(f'/birds_app/bird/{bird.id}')
        return render(request, 'bird-details.html', {'form': form})

class AddBirdToWishlist(LoginRequiredMixin, View):
    def get(self, request):
        form = WishListForm(request.user)
        return render(request, 'wish_list.html', {'form': form})
    def post(self, request):
        form = WishListForm(request.user, request.POST)
        if form.is_valid():
            wishlist = form.save(commit=False)
            wishlist.user = request.user
            wishlist.save()
            return redirect('wish-list')
        return render(request, 'wish_list.html', {'form': form})


class ButtonWishlist(LoginRequiredMixin, View):
    def get(self, request, id):
        bird = Birds.objects.get(pk=id)
        return render(request, 'bird-details.html', {'bird': bird})
    def post(self, request, id):
        bird = Birds.objects.get(pk=id)
        form = WishListForm(request.POST)
        if form.is_valid():
            wishlist = form.save(commit=False)
            wishlist.user = request.user
            wishlist.save()
            return redirect('wish-list')
        return render(request, 'wish_list.html', {'form': form})


class QuizView(View):
    def get(self, request):
        quiz = Quiz.objects.get(name='Ultimate Bird Quiz')
        questions = quiz.question_set.all()
        return render(request, 'quiz.html', {'quiz': quiz, 'questions': questions})

    def post(self, request):
        quiz = Quiz.objects.get(name='Ultimate Bird Quiz')
        questions = quiz.question_set.all()
        score = 0
        wrong = 0
        correct = 0
        total = 0
        for q in questions:
            total += 1
            answer_id = int(request.POST.get(str(q.id), 0))
            correct_answer = q.answer_set.get(correct=True)
            if correct_answer.id == answer_id:
                score += 10
                correct += 1
            else:
                wrong += 1
        percent = score / (total * 10) * 100
        ctx = {
            'score': score,
            'correct': correct,
            'wrong': wrong,
            'percent': percent,
            'total': total
        }
        return render(request, 'quiz_results.html', ctx)




# class QuizView(View):
#     def get(self, request):
#         questions = Quiz.objects.all()
#         return render(request, 'quiz.html', {'questions': questions})
#     def post(self, request):
#         questions = Quiz.objects.all()
#         score = 0
#         wrong = 0
#         correct = 0
#         total = 0
#         for q in questions:
#             total += 1
#             print(request.POST.get(q.question))
#             print(q.answer)
#             print()
#             if q.answer == request.POST.get(q.question):
#                 score += 10
#                 correct += 1
#             else:
#                 wrong += 1
#             percent = score / (total * 10) * 100
#         ctx = {
#             'score': score,
#             'correct': correct,
#             'wrong': wrong,
#             'percent': percent,
#             'total': total
#         }
#         return render(request, 'quiz_results.html', ctx)

birds_app/templates/add-comment.html
{% extends 'main.html' %}
{% block sikorka %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
{{ form.as_p }}
<input type="submit">
</form>



{% endblock %}

birds_app/templates/add_bird.html
{% extends 'main.html' %}
{% block sikorka %}
    <div class="container">
      <center><h1>Add your bird!</h1></center>
</div>

<center><form method="post" enctype="multipart/form-data" style="margin: 20px">
    {% csrf_token %}
{{ form.as_p }}
<input type="submit" class="button3">
{{ text }}
</form></center>


{% endblock %}

birds_app/templates/bird-details.html
{% extends 'main.html' %}
{% block sikorka %}

<section class="detail-bird-layout">

<ul>
    <center><h2 style="margin: 20px">{{ bird.name }} </h2></center>
    <li style="margin: 10px"><b>Description:</b> {{ bird.description }}</li>
    <li style="margin: 10px"><b>Family:</b> {{ bird.family }}</li>
    <li style="margin: 10px"><b>Population:</b> {{ bird.population }}</li>
</ul>

    <div>
    <img src="{{ bird.get_main_image_url }}" style="width: 100%; float: left; margin-right: 10px;"/>
</div>

</section>
{% if user.is_superuser %}
<a href="/birds_app/bird/{{ bird.id }}/edit/">
<button class="button2">Edit bird</button></a>
    {% endif %}

<a href="{% url 'wish-list' %}">
<button class="button2" id="wishlist">Add to your Wishlist</button></a>


        <a href="/birds_app/bird/{{ bird.id }}/comment/">
<button class="button2">Add comment</button></a>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
{{ form.as_p }}
<input type="submit">
</form>

<section>
    <div style="width: 30%; margin: 10px; padding: 5px; font-weight: bold; box-shadow: #444444 2px 3px; border: #666666 ">Users Comments</div>
    {% for comment in comments %}

    <div style="width: 30%; margin: 10px; padding: 5px; font-weight: bold; box-shadow: #444444 2px 3px; border: #666666 ">Autor: {{ comment.author }}</div>
    <div style="width: 30%; height: fit-content; margin: 10px; padding: 5px; box-shadow: #444444 2px 3px; border: #666666 ">{{ comment.text }}</div>

    {% endfor %}
</section>

{% endblock %}

birds_app/templates/bird_list.html
{% extends 'main.html' %}
{% block sikorka %}

<div class="container">
      <center><h1>Birds of Poland</h1></center>
      </div>

<section class="div-layout">
    {% for bird in birds %}
<div class="card" style="width: 17rem; margin: 10px">
    <img src="{{ bird.get_main_image_url }}" class="card-img-top" alt="Bird"/>
    <div class="card-body">
    <h5 class="card-title">{{ bird.name }}</h5>
    <a href="/birds_app/bird/{{ bird.id }}" class="btn btn-outline-dark">Read more!</a>
    </div>
</div>
    {% endfor %}
</section>

    {% if user.is_authenticated %}
<center>
        <a href="/birds_app/add-bird/">
<button class="button3">Add bird</button>
</a></center>
    {% endif %}

{% endblock %}

birds_app/templates/bird_search.html
{% extends 'main.html' %}
{% block sikorka %}

    {% if searched_bird %}
        <center><h2>You searched for:</h2></center>
    {{ searched_bird }}
        
        {% else %}
        <center><h2>No bird found</h2></center>
    {% endif %}

{% endblock %}

birds_app/templates/form.html
{% extends 'main.html' %}
{% block sikorka %}

<form method="post">
    {% csrf_token %}
{{ form.as_p }}
<input type="submit" class="button3">
</form>

{% endblock %}

birds_app/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
     <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
     <!-- animate css link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

    <!-- google font link -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Coiny&display=swap" rel="stylesheet">

    <title>Birds</title>
</head>
<body>

<div class="topnav">
    <a href="{% url 'main' %}">
        <img src="https://cdn.pixabay.com/photo/2014/03/25/16/57/bird-297691_960_720.png" width="35px" height="35px">
    </a>
    <a href="{% url 'main' %}">Birds of Poland</a>
    <a href="{% url 'bird-list' %}">Birds</a>
    <a href="{% url 'add-bird' %}">Add Bird</a>
    <a href="{% url 'wish-list' %}">Wish List</a>
    <a href="{% url 'quiz' %}">Quiz</a>
    {% if user.is_authenticated %}
    <a href="{% url 'logout' %}">LogOut</a>
    {% else %}
    <a href="{% url 'register' %}">Register</a>
    <a href="{% url 'login' %}">LogIn</a>
    {%  endif %}
</div>

{% block sikorka %}

<div class="container">
      <center><h1>Birds of Poland</h1></center>
      <center>Welcome to the site. <a href="{% url 'register' %}">Register</a> or <a href="{% url 'login' %}">LogIn</a> to access all site's options!</center>
</div>
<!-- slider section -->
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            {% for object in carousel %}
            <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
                <img src="{{object.image.url}}" style="height:650px;" class="testi-overly d-block w-100" alt="sliderImg">
                <div class="carousel-caption d-none d-md-block">
                    <h1 class="animate__animated
                    {% if forloop.counter0 == 0 %}
                    animate__fadeInDown
                    {% endif %}
                    {% if forloop.revcounter == 1 %}
                    animate__bounce
                    {% endif %}
                    {% if forloop.revcounter == 2 %}
                    animate__fadeInRight
                    {% endif %}">{{object.title}}</h1>
                    <h3 class="animate__animated animate__zoomIn"></h3>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>


<br>
<!-- statistics section -->
            <div class="container2">
                    <div class="col text-center">
                        <h2><b> Number of birds:</b></h2>
                        <h2>{{ birds_number }}</h2>
                    </div>
                    <div class="col text-center">
                        <h2><b>Number of users:</b></h2>
                        <h2>{{ users_number }}</h2>
                    </div>
                    <div class="col text-center">
                        <h2><b>Number of images</b></h2>
                        <h2>{{ image_number }}</h2>
                    </div>
            </div>

<br>

    <!-- Bird of the day section -->
    <div class="container">
      <center><h1>Bird of the day!</h1></center>
</div>

<center><div class="card mb-3" style="width: 70%">
  <img src="{{ random_bird.get_main_image_url }}" class="card-img-top" alt="Bird of the day">
  <div class="card-body">
    <h2 class="card-title">{{ random_bird.name }}</h2>
    <p class="card-text">{{ random_bird.description }}</p>
    <a href="/birds_app/bird/{{ random_bird.id }}" class="btn btn-outline-dark">Read more!</a>
  </div>
</div></center>
    <br>

<!-- Bird search section -->

<img src="https://static.wikia.nocookie.net/starwars/images/4/47/Porg_wings_Fathead.png/revision/latest?cb=20180830034728" style="width: 30%; float: left; margin-right: 50px;">

<form method="get" class="form-check-label">
    <div>
        <label><b>Find your birdy!</b></label>
        <input type="text" name="search">
        <button type="submit" name="button" class="btn btn-outline-dark">Search</button>
    </div>
</form>

    <br>
    <br>
    <br>

    {% for bird in birds %}
<li style="text-align: center"><a href="/birds_app/bird/{{ bird.id }}">{{ bird.name }}</a></li>
    {% endfor %}


<br>
{% endblock %}

<div class="footer1">
    <p> Użytkownik {{ user }}</p>
</div>

<!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>

</body>
</html>

birds_app/templates/quiz.html
{% extends 'main.html' %}
{% block sikorka %}
<center><form method='post' action='' style="margin: 20px">
    {% csrf_token %}
<div class="container">
      <h1>{{ quiz.name }}</h1>
    <h3>{{ quiz.description }}</h3>
      </div>
<br>
<br>
    {% for q in questions%}
    <div>
      <h5><b>{{q.question}}</b></h5>
    </div>
        {% for a in q.answer_set.all %}
         <div>
            <input type="radio" name="{{q.id}}" value="{{ a.id }}" >
            <label>{{a.answer}}</label>
        </div>
            <br>
    {% endfor %}
{% endfor %}
    <button type="submit" class="button3">Submit</button>

</form></center>
{% endblock %}

birds_app/templates/quiz_results.html
{% extends 'main.html' %}
{% block sikorka %}

<div class="container" style="margin: 20px">
    <div style="padding: 10px; margin: 10px;">
        <div align="centre" style="width: 32rem">
                <h4 class="card-title"><b>Score: {{score}}</b></h4>
                <p>Correct answers: {{correct}}</p>
                <p class="card-text">Incorrect answers: {{wrong}}</p>
                <p class="card-text">Percentage: {{percent}}%</p>
                <p class="card-text">Total questions: {{total}}</p>
                <h4><b>Good luck with the next quiz!</b></h4>
        </div>
    </div>
</div>
<img src="https://static.wikia.nocookie.net/starwars/images/4/47/Porg_wings_Fathead.png/revision/latest?cb=20180830034728" style="width: 30%;">


{% endblock %}

birds_app/templates/wish_list.html
{% extends 'main.html' %}
{% block sikorka %}

    <div class="container">
      <center><h1>Add birds to your wish list!</h1></center>
</div>

    <center><form method="post" enctype="multipart/form-data" class="form-check-inline" style="width: 40%">
    {% csrf_token %}
{{ form.as_p }}
<input type="submit" class="button3">
    </form></center>

        <div class="container">
      <center><h1>My wish list!</h1></center>
</div>

<section class="div-layout">

    {% for item in user.wishlist_set.all %}
<div class="card" style="width: 17rem; margin: 10px">
    <img src="{{ item.birds.get_main_image_url }}" class="card-img-top" alt="Bird"/>
    <div class="card-body">
    <h5 class="card-title">{{ item.birds.name }}</h5>
    <a href="/birds_app/bird/{{ item.birds.id }}" class="btn btn-outline-dark">Read more!</a>
    </div>

</div>
        {% endfor %}

 </section>

</form>
{% endblock %}